# Generated by Django 3.0.4 on 2020-05-18 22:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dastosUsuario', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='datos',
            name='email',
            field=models.EmailField(default=2, max_length=254, verbose_name='Correo'),
            preserve_default=False,
        ),
    ]
