# Generated by Django 3.0.4 on 2020-05-19 04:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dastosUsuario', '0003_auto_20200518_1729'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='datos',
            name='usuario',
        ),
    ]
