# Generated by Django 3.0.4 on 2020-05-20 02:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dastosUsuario', '0005_auto_20200519_0019'),
    ]

    operations = [
        migrations.RenameField(
            model_name='datos',
            old_name='idenfication',
            new_name='identification',
        ),
    ]
