# Generated by Django 3.0.4 on 2020-08-18 23:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dastosUsuario', '0006_auto_20200519_2115'),
    ]

    operations = [
        migrations.AddField(
            model_name='datos',
            name='avatar',
            field=models.ImageField(default=2, upload_to='dastosUsuario', verbose_name='Avatar'),
            preserve_default=False,
        ),
    ]
