# Generated by Django 3.0.4 on 2020-04-30 06:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('categoriasblog', '0001_initial'),
        ('blog', '0004_post_categories'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='categories',
            field=models.ManyToManyField(to='categoriasblog.Category', verbose_name='Categorías'),
        ),
    ]
