# Generated by Django 3.0.4 on 2020-04-30 06:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('categoriasblog', '0001_initial'),
        ('blog', '0006_auto_20200430_0143'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='categories',
        ),
        migrations.AddField(
            model_name='post',
            name='categories',
            field=models.ForeignKey(default=2, on_delete=django.db.models.deletion.CASCADE, related_name='categories', to='categoriasblog.Category', verbose_name='Categorías'),
            preserve_default=False,
        ),
    ]
