# Generated by Django 3.0.4 on 2020-05-15 07:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0007_auto_20200430_0148'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='image_banner',
            field=models.ImageField(blank=True, null=True, upload_to='blog', verbose_name='Imagen banner'),
        ),
    ]
